# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '16.x'

    - name: Install newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make Directory for results
      run: |
        git rm -r test-results
        git rm -r newman
        mkdir -p test-results
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 80 chars wide
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=80 --statistics > test-results/flake8.txt
    - name: Test with unittest
      env:
          DBUSER: marc1_test
          DBPASSWORD: marc1
          DBHOST: fern.c5hb0sp2qrhh.us-east-2.rds.amazonaws.com
          RDBSCHEMA: marc1_testing
          MONGO_URL: "mongodb+srv://admin_marc1:marc1@cluster0.90pjm.mongodb.net/Form_test?retryWrites=true&w=majority"
      run: |
        coverage run -m unittest discover -v
        coverage xml -o coverage-reports/*coverage-*.xml
        coverage html -d test-results/coverage/
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Postman
      run: |
        newman run ./postman/Form-Hoster-Test.postman_collection.json -e ./postman/Production.postman_environment.json --reporters cli,htmlextra
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add --force test-results newman
        git commit -m "Uploading test reports"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
